networks:
  nginx-proxy_default:
    external: true
services:
  editor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_BUILDKIT=1
      # no_cache: true
    working_dir: /app
    ports:
      - "9015:3001"
    env_file:
      - ./backend/.env
    networks:
      - nginx-proxy_default
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
